# Generated by Django 5.1.7 on 2025-04-30 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PopularBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_images/')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popularbusiness.category')),
            ],
        ),
    ]
