# Generated by Django 5.1.7 on 2025-05-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price in Philippine Peso (PHP)', max_digits=10)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('address', models.CharField(help_text='User-selected address for the service', max_length=255)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the selected location', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the selected location', null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Reply to the review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5')),
                ('rating_label', models.CharField(choices=[('Poor', 'Poor'), ('Needs Improvement', 'Needs Improvement'), ('Average', 'Average'), ('Good Job', 'Good Job'), ('Excellent Job', 'Excellent Job')], help_text='Descriptive rating label', max_length=50)),
                ('comment', models.TextField(blank=True, help_text="Customer's review comment")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('repair', 'Repair'), ('painting', 'Painting'), ('plumbing', 'Plumbing'), ('electric', 'Electric')], default='cleaning', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Philippine Peso (PHP)', max_digits=10)),
            ],
        ),
    ]
